apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
      - name: ai
        image: DOCKER_REGISTRY/ai:BUILD_NUMBER
        ports:
          - name: http-port
            containerPort: 80

