version: "2"

services:
  webui:
    build: files
    depends_on:
        - postgres
    ports:
    - "3000:3000"
    volumes:
    - "./files/:/files/"

  postgres:
    image: postgres
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: kubechess
    volumes:
        - ./pgdata:/var/lib/postgresql/data
        - ./db:/docker-entrypoint-initdb.d/
    ports:
        - '5432:5432'
